export enum MessageTypes {
    "INSTALLED" = "INSTALLED",
    "UPDATED" = "UPDATED",
    "UNINSTALLED" = "UNINSTALLED",
    "SUBURBADDED" = "SUBURBADDED",
    "SUBURBREMOVED" = "SUBURBREMOVED",
    "SUBURBVIEWED" = "SUBURBVIEWED",
    "DAYSCHANGED" = "DAYSCHANGED"

}
