# This GitHub Action checks if a pull request targeting the master branch 
# has one of the specified "DO NOT MERGE" labels, and if it does, 
# it will block the merge by failing the action

name: Check for DO NOT MERGE labels

on:
  pull_request:
    branches: [ master ]
    # The action is triggered when a label is added (labeled), removed (unlabeled), 
    # or when the pull request is synchronized (synchronize).
    types: [labeled , unlabeled, synchronize ] 

jobs:
  fail-for-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DO NOT MERGE label
        if: contains(github.event.pull_request.labels.*.name, 'Do not merge') ||
            contains(github.event.pull_request.labels.*.name, 'o_not_merge')    
        run: |
          exit 1