# This GitHub Action checks if a pull request targeting the master branch 
# has one of the specified "DO NOT MERGE" labels, and if it does, 
# it will block the merge by failing the action

name: Check for DO NOT MERGE labels

on:
  pull_request:
    branches: [ master ]
    types: [labeled , unlabeled, synchronize ]

jobs:
  fail-for-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DO NOT MERGE label
        if: github.event.pull_request.labels.*.name in ['Do NOT MERGE', 'Dont Merge']
        run: |
          exit 1